---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, Workload Factory, builders, Workload Factory, EDA, electronic design automation' 
summary: Découvrez les nouveautés de Workload Factory pour EDA. 
---
= Nouveautés de NetApp Workload Factory pour EDA
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés concernant les fonctionnalités EDA de Workload Factory.



== 4 janv. 2026



=== NetApp Workload Factory for Builders devient NetApp Workload Factory for EDA

Workload Factory for Builders s'appelle désormais Workload Factory for EDA. Ce changement de nom reflète l'accent mis sur les charges de travail d'automatisation de la conception électronique (EDA).

Workload Factory pour EDA vous aide à optimiser FSx pour ONTAP sur plusieurs systèmes de fichiers. Vous pouvez optimiser les performances et réduire les coûts opérationnels en automatisant les paramètres de stockage, en analysant les contraintes de performance et en obtenant des informations sur les projets EDA. Workload Factory pour EDA est conçu pour s'intégrer à vos frameworks d'infrastructure en tant que code (IaC).



=== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



== 5 octobre 2025



=== BlueXP workload factory désormais NetApp Workload Factory

BlueXP a été renommé et repensé pour mieux refléter le rôle qu'il joue dans la gestion de votre infrastructure de données. Par conséquent, BlueXP workload factory a été renommée NetApp Workload Factory.



== 16 juin 2025



=== Prise en charge des clones

Vous pouvez désormais cloner un projet dans BlueXP Workload Factory for Builders. Lorsque vous clonez un projet, Builders crée un nouveau projet à partir d'un instantané, avec la même configuration que l'original. Le clonage est utile pour créer rapidement des projets similaires ou à des fins de test. Vous pouvez monter le nouveau clone de projet en suivant les instructions dans Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Gérer les versions des projets BlueXP Workload Factory pour les constructeurs"]



== 4 mai 2025



=== Terminologie des autorisations mise à jour

L'interface utilisateur et la documentation de Workload Factory utilisent désormais « lecture seule » pour désigner les autorisations de lecture et « lecture/écriture » pour désigner les autorisations d'automatisation.



== 1er décembre 2024



=== Version initiale de la charge de travail des constructeurs

BlueXP Workload Factory for Builders simplifie la consommation et l'accès aux versions logicielles, éliminant ainsi le besoin d'outils ou de scripts personnalisés. Il vous permet d'utiliser des versions logicielles sous forme de clones instantanés intégrés à Perforce Helix Core, offrant ainsi un espace de travail pratique pour vos processus de développement et vous permettant de gagner du temps et des ressources.

La version initiale inclut la possibilité de gérer des projets et des espaces de travail, et d'automatiser des actions avec Codebox. Vous pouvez également intégrer Builders à Perforce Helix Core, afin de gérer différentes versions de chaque projet et de passer rapidement de l'une à l'autre.
